-- ============================================================
--  SQL para Tabela `stickers` – Bonequinhas da Dani
--  Execute este código no SQL Editor do seu projeto Supabase.
-- ============================================================

-- 1. CRIAÇÃO DA TABELA `stickers`
-- Armazena os metadados de cada figurinha.
CREATE TABLE public.stickers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  category text NOT NULL,
  title text,
  caption text,
  image_url text NOT NULL,
  status text DEFAULT 'public'::text NOT NULL, -- 'public' ou 'pending'
  created_by uuid -- Opcional: pode ser vinculado ao user se houver autenticação
);

-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
-- Essencial para proteger seus dados.
ALTER TABLE public.stickers ENABLE ROW LEVEL SECURITY;

-- 3. POLICIES (REGRAS DE ACESSO)
-- Define quem pode fazer o quê na tabela.

-- POLICY 1: Permitir leitura pública para todos.
-- Qualquer pessoa (autenticada ou não) pode ver as figurinhas com status 'public'.
CREATE POLICY "Allow public read access" ON public.stickers
  FOR SELECT
  USING (status = 'public');

-- POLICY 2: Permitir que qualquer pessoa (anon) crie novas figurinhas.
-- A validação do "Código da Comunidade" é feita no front-end (app.js).
-- O Supabase usa a chave `anon` para essas inserções.
CREATE POLICY "Allow anonymous insert" ON public.stickers
  FOR INSERT
  WITH CHECK (true);

-- ============================================================
--  CONFIGURAÇÃO DO STORAGE (BUCKET)
-- ============================================================

-- 1. CRIE O BUCKET `stickers`
-- Vá para a seção Storage no painel do Supabase e crie um novo bucket.
-- NOME: stickers
-- ACESSO PÚBLICO: Marque esta opção.

-- 2. POLICIES DO STORAGE
-- As policies abaixo garantem que todos possam ver as imagens,
-- mas apenas usuários anônimos (via app) possam fazer upload.

-- POLICY 1: Permitir SELECT (leitura/visualização) para todos.
CREATE POLICY "Allow public read access on stickers" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'stickers');

-- POLICY 2: Permitir INSERT (upload) para anônimos.
CREATE POLICY "Allow anonymous upload on stickers" ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'stickers');

-- NOTA: Não são necessárias policies de UPDATE ou DELETE para este projeto,
-- o que aumenta a segurança, pois uma vez enviada, a figurinha não pode
-- ser alterada ou removida por um usuário comum através da API pública.
